[[redirects]]
  from = "/brochure"
  to = "/brochure.pdf"
  status = 200

[[redirects]]
  from = "/register"
  to = "https://nirmalkarthikeyan.typeform.com/to/YGTSe31n"

[[redirects]]
  from = "/inauguration"
  to = "https://teams.microsoft.com/l/meetup-join/19%3ameeting_NDBjN2M1YmMtZjJiMS00M2VmLWEwYjktYTU1YzVhYzRkNGY5%40thread.v2/0?context=%7b%22Tid%22%3a%2200f9cda3-075e-44e5-aa0b-aba3add6539f%22%2c%22Oid%22%3a%22d721681b-7ad3-4b5c-b2c3-a012369e365f%22%7d"

[[redirects]]
  from = "/gitworkshop"
  to = "https://teams.microsoft.com/l/meetup-join/19%3Ameeting_NDBjN2M1YmMtZjJiMS00M2VmLWEwYjktYTU1YzVhYzRkNGY5%40thread.v2/0?context=%7B%22Tid%22%3A%2200f9cda3-075e-44e5-aa0b-aba3add6539f%22%2C%22Oid%22%3A%22d721681b-7ad3-4b5c-b2c3-a012369e365f%22%2C%22MessageId%22%3A%220%22%7D"
  status = 200
  
[[redirects]]
  from = "/webworkshop"
  to = "https://teams.microsoft.com/l/meetup-join/19%3Ameeting_NDBjN2M1YmMtZjJiMS00M2VmLWEwYjktYTU1YzVhYzRkNGY5%40thread.v2/0?context=%7B%22Tid%22%3A%2200f9cda3-075e-44e5-aa0b-aba3add6539f%22%2C%22Oid%22%3A%22d721681b-7ad3-4b5c-b2c3-a012369e365f%22%2C%22MessageId%22%3A%220%22%7D"
  status = 200

[[redirects]]
  from = "/appdevworkshop"
  to = "https://teams.microsoft.com/l/meetup-join/19%3Ameeting_NDBjN2M1YmMtZjJiMS00M2VmLWEwYjktYTU1YzVhYzRkNGY5%40thread.v2/0?context=%7B%22Tid%22%3A%2200f9cda3-075e-44e5-aa0b-aba3add6539f%22%2C%22Oid%22%3A%22d721681b-7ad3-4b5c-b2c3-a012369e365f%22%2C%22MessageId%22%3A%220%22%7D"
  status = 200

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/tgsNgVQ8Gd"
